export const PAYMENT_DETAILS = 'PAYMENT_DETAILS'

export const GET_TRANSACTIONS = 'GET_TRANSACTIONS'

export const PAYMENT = 'PAYMENT'
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS'
export const PAYMENT_FAILED = 'PAYMENT_FAILED'


